### ISSUE TITLE
Can't connect to the panel

### ISSUE THREAD

**Issue by 4liPoker** [Ashaxer/VirtualizorPanel#1]
hello After entering the API, the information is not confirmed, not even canceled

**Comment by Ashaxer** [comment]
-Fixed

**Comment by Ashaxer** [comment]
-Fixed

**Comment by 4liPoker** [comment]
If possible, give me your email address or telegram ID so I can show you, the robot is not fixed yet!

**Comment by Ashaxer** [comment]
Maybe you are using non-secure http port for connecting to panel (I fixed it in new version but still maybe that is the issue)
For example use 4083 instead of 4082
You can write me here:
https://Shaxerver_Admin.t.me
